### ISSUE TITLE
Recreate old frontend

### ISSUE THREAD

**Issue by Reffx** [Master-Project-RNG/rgntrainer_frontend#4]
Implement the old frontend with flutter.

**Screens**
- [x] Login Screen (#5)
- [x] Admin screen (login as admin) (#6)
- [x] User screen (login as user) (#7)

**Functionalities**
- [x] Reimplement the GET & POST requests (#14, #15)
