### ISSUE TITLE
Results Screen per bureau (admin)

### ISSUE THREAD

**Issue by Reffx** [Master-Project-RNG/rgntrainer_frontend#64]
- [x] #67: update the columns
- [x] #68: Move download results to result screen
- [x] #71: Hide columns in the table
